### ISSUE TITLE
Naçizane öneri

### ISSUE THREAD

**Issue by doanaktar** [edisdev/edisdev.github.io#1]
çatır çtur parmaklarını - parmaklarını çatır çutur
üniversite sınava girerken - üniversite sınavına girerken ki
“Bilgisayar Mühendisi” olmaktadı - “Bilgisayar Mühendisi” olmaktı
Daha doğrusu ben öyle sanıyorum o zamanlar - Daha doğrusu ben öyle sanıyordum o zamanlar
aslında yazılım öğreniyorduk zaten giriş seviyesi de olsa - aslında giriş seviyesi de olsa yazılım öğreniyorduk
bilgisayarım yanındaydı -  bilgisayarım yanımdaydı
Daha çok çalışmaya çabalamaya devam ettim .. - Daha çok çalışmaya, çabalamaya devam ettim ..

**Comment by edisdev** [comment]
Selam @doganaktarr  🖐 Şimdiye kadar bunları fark eden olmamış, ben de fark etmemişim 😞 Önerin için çok teşekkür ederim🙏 Yakın zamanda sitemi yenilemeyi düşünüyordum, eğer bugün veya yarın yapamazsam veya aynı metin kullanırsam düzelteceğim mutlaka 😊

**Comment by edisdev** [comment]
Tekrar selam @doganaktarr  :) Düzeltmeleri yaptım, tekrar çok çok teşekkür ederim 👍  💯

**Comment by doanaktar** [comment]
Ne demek, rica ederim iyi çalışmalar :)
